### ISSUE TITLE
Image dimension for ploting 

### ISSUE THREAD

**Issue by dcharua** [kevinzakka/tsne-viz#2]
Hello, first let me congratulate for an excellent code. It's well documented and well written. All the other plots that are tried were not good enough to understand the data, this one is very clear.
Anyway to the point. I tried it with my own dataset, I'm able to plot in 3d and 2d, as well as to do the embedding, but I cannt overlay the images, I get the following error

> Traceback (most recent call last):
>   File "main.py", line 134, in <module>
>     main(config)
>   File "main.py", line 115, in main
>     im = OffsetImage(X_sample[i], zoom=0.1, cmap='gray')
>   File "/usr/local/lib/python3.5/dist-packages/matplotlib/offsetbox.py", line 1300, in __init__
>     self.set_data(arr)
>   File "/usr/local/lib/python3.5/dist-packages/matplotlib/offsetbox.py", line 1304, in set_data
>     self.image.set_data(self._data)
>   File "/usr/local/lib/python3.5/dist-packages/matplotlib/image.py", line 653, in set_data
>     raise TypeError("Invalid dimensions for image data")
> TypeError: Invalid dimensions for image data

My X_sample is of shape (5000, 3, 32, 32)
where 5000 is the data size
X_sample[i].shape is (3, 32, 32)

What is the correct dimension? 

Thank you for your time and code

**Comment by simplystart-from-begining** [comment]
I'm lucky to be able to focus on your work,l'm trying this code with my own datasets,but i'm not able to plot in 2d and 3d,i get  error  ''KeyError: 'train_imgs''
what's the correct code and command?thanks in advance

**Comment by dcharua** [comment]
Not sure what the question is, but I worked on this project a few months ago, you can see my code adaptation in this [repo](https://github.com/dcharua/T-Sne)

**Comment by ChengYanLong-graduate** [comment]
I'm sorry that I didn't have a clear description of the problems I have encountered last time.
when I was executing this program,I met the following error:
  File "main.py", line 23, in main
    X_train, y_train, _, _ = load_data(config.data_dir)
  File "/home/chengyanlong/桌面/tsne-viz-master/utils.py", line 65, in load_data
    X_train = data['train_imgs']
KeyError: 'train_imgs'

I find 'num_files = len(names) ' actually is 0
How to solve this error? I hope get your help,thanks a lot

**Comment by simplystart-from-begining** [comment]
thanks a lot to your reply.i have reviewed your code adaptation,what about your 'data4torch.h5' file?I hope get your help,thanks in advance.
17717153347@163.com
